version: "3"

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "8080:443"
    tty: true
    networks:
      - wordpress
    volumes:
      - ./requirements/tools/www:/var/www/html/
    # depends_on:
    #   wordpress:
    #     condition: service_healthy

  wordpress:
    build: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - ./requirements/tools/www:/var/www/html/
    tty: true
    networks:
      - wordpress
    expose:
      - 9000

  mariadb:
    build: ./requirements/mariadb
    env_file:
      - .env
    # volumes:
    #   - my-mariadb-data:/var/lib/mysql
    volumes:
      - ./requirements/tools/db:/var/lib/mysql/
    tty: true
    networks:
      - wordpress
    expose:
      - 3306

networks:
  wordpress:

# volumes:
#   my-mariadb-data:
