version: "3"

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
      - "80:80"
    tty: true
    networks:
      - wordpress
    volumes:
      # - ./requirements/tools/www:/var/www/html/
      - nginx-volume:/var/www/html/

  wordpress:
    build: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      # - ./requirements/tools/www:/var/www/html/
      - nginx-volume:/var/www/html/
    tty: true
    networks:
      - wordpress
    expose:
      - 9000

  mariadb:
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
    # - ./requirements/tools/db:/var/lib/mysql/
    - mariadb-volume:/var/lib/mysql/
    tty: true
    networks:
      - wordpress
    expose:
      - 3306

networks:
  wordpress:

volumes:
  mariadb-volume:
    driver_opts:
      type: none
      device: /home/wchen/data/db
      o: bind
  nginx-volume:
    driver_opts:
      type: none
      device: /home/wchen/data/wp
      o: bind